name: "Modena Interiors"
description: "Interior Refurbishment Solutions"
exclude: [Gemfile, Gemfile.lock]
timezone: Europe/London

contact_number: "0772 8032 929"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
