name: "Modena Interiors"
description: "Interior Refurbishment Solutions"
exclude: ["Gemfile", "Gemfile.lock", "Gemfile.lock", "README.md", "assets/fonts", "assets/javascripts/bootstrap/"]
timezone: Europe/London
hostname: "modena-interiors.com"

baseurl: ""

sass:
  sass_dir: "assets/stylesheets" 

contact_number: "07728032929"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


google_analytics: "UA-56546821-1"
